In [1]:
import pandas as pd

In [2]:

df = pd.read_csv('tracks_enriched.csv', sep='\t')
df

,song_id,album_id,track_number,release_date_x,release_date_precision_x,name,billboard,artists,popularity,total_tracks,...,year_end_score,is_pop,year,rank_score,peak_position,week_count,date,artist_id,release_date_y,release_date_precision_y
0,3e9HZxeyfWwjeyPAMmWSSQ,2fYhqwDWXjbpjaIJPEfKFw,11,2019-02-08,day,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5p7ujcrUXASCNwRaWNHR1C,0zzrCTzvL4ZmR42xF46Afm,1,2018-10-04,day,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2xLMifQCjDGFmkHkpNLD9h,41GuZcammIkupMPKH2OJ6I,3,2018-08-03,day,ASTROWORLD,ASTROWORLD,{'0Y5tJX1MQlPlqiwlOH1tJY': 'Travis Scott'},91.0,17.0,...,4210.0,True,2018.0,195.0,200.0,20.0,2018-12-29,0Y5tJX1MQlPlqiwlOH1tJY,2018-08-03,day
3,2xLMifQCjDGFmkHkpNLD9h,41GuZcammIkupMPKH2OJ6I,3,2018-08-03,day,ASTROWORLD,ASTROWORLD,{'0Y5tJX1MQlPlqiwlOH1tJY': 'Travis Scott'},91.0,17.0,...,4210.0,True,2018.0,195.0,200.0,19.0,2018-12-22,0Y5tJX1MQlPlqiwlOH1tJY,2018-08-03,day
4,2xLMifQCjDGFmkHkpNLD9h,41GuZcammIkupMPKH2OJ6I,3,2018-08-03,day,ASTROWORLD,ASTROWORLD,{'0Y5tJX1MQlPlqiwlOH1tJY': 'Travis Scott'},91.0,17.0,...,4210.0,True,2018.0,193.0,200.0,18.0,2018-12-15,0Y5tJX1MQlPlqiwlOH1tJY,2018-08-03,day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1986380,30342v7I9sUoNC0Djnu1mW,1bZHbHtUvjGqUOKNla4lo0,25,2000-01-01,day,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1986381,5rkgbGIOTBGlKTAawWb06X,3GmCXW10kLxmZrEY0JpRlw,9,1988-03-07,day,Past Masters (Vols. 1 & 2 / Remastered),Past Masters,{'3WrFJ7ztbogyGnTHbHJFl2': 'The Beatles'},61.0,33.0,...,73.0,False,2010.0,47.0,47.0,2.0,2010-01-09,3WrFJ7ztbogyGnTHbHJFl2,1988-03-07,day
1986382,5rkgbGIOTBGlKTAawWb06X,3GmCXW10kLxmZrEY0JpRlw,9,1988-03-07,day,Past Masters (Vols. 1 & 2 / Remastered),Past Masters,{'3WrFJ7ztbogyGnTHbHJFl2': 'The Beatles'},61.0,33.0,...,73.0,False,2010.0,24.0,24.0,0.0,2010-01-02,3WrFJ7ztbogyGnTHbHJFl2,1988-03-07,day
1986383,2MVPsa4S4r7Ii5lMh85E03,0UiVuqXa69zXqql0GoXH2h,22,2013-01-31,day,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1986384,7wGbzk3aeGSpnsK2AQ7vzA,3pBArpt3QcnvVj58hl6Ghe,7,2012-05-31,day,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# how many nan's in each column
nan_counts = df.isna().sum()
nan_counts

song_id                        0
album_id                       0
track_number                   0
release_date_x                 0
release_date_precision_x       0
name                        9105
billboard                   9105
artists                     9105
popularity                  9105
total_tracks                9105
album_type                  9105
image_url                   9105
year_end_score              9112
is_pop                      9112
year                        9112
rank_score                  9112
peak_position               9112
week_count                  9112
date                        9112
artist_id                   9105
release_date_y              9105
release_date_precision_y    9105
dtype: int64

In [5]:
df2 = pd.read_csv('artists_enriched.csv', sep='\t')
df2

/var/folders/nw/0j298g817b92m2qlhw1_fwnr0000gn/T/ipykernel_42300/871867837.py:1: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv('artists_enriched.csv', sep='\t')

,artist_id,name,followers,popularity,artist_type,main_genre,genres,image_url,year_end_score,is_pop,year,rank_score,peak_position,weeks_on_chart,week
0,66CXWjxzNUsdJxJ2JdwvnR,Ariana Grande,34554242.0,96,singer,dance pop,"['dance pop', 'pop', 'post-teen pop']",https://i.scdn.co/image/b1dfbe843b0b9f54ab2e58...,26508.0,True,2018.0,457.0,665.0,171.0,2018-12-29
1,66CXWjxzNUsdJxJ2JdwvnR,Ariana Grande,34554242.0,96,singer,dance pop,"['dance pop', 'pop', 'post-teen pop']",https://i.scdn.co/image/b1dfbe843b0b9f54ab2e58...,26508.0,True,2018.0,448.0,681.0,189.0,2018-12-22
2,66CXWjxzNUsdJxJ2JdwvnR,Ariana Grande,34554242.0,96,singer,dance pop,"['dance pop', 'pop', 'post-teen pop']",https://i.scdn.co/image/b1dfbe843b0b9f54ab2e58...,26508.0,True,2018.0,486.0,681.0,184.0,2018-12-15
3,66CXWjxzNUsdJxJ2JdwvnR,Ariana Grande,34554242.0,96,singer,dance pop,"['dance pop', 'pop', 'post-teen pop']",https://i.scdn.co/image/b1dfbe843b0b9f54ab2e58...,26508.0,True,2018.0,462.0,680.0,179.0,2018-12-08
4,66CXWjxzNUsdJxJ2JdwvnR,Ariana Grande,34554242.0,96,singer,dance pop,"['dance pop', 'pop', 'post-teen pop']",https://i.scdn.co/image/b1dfbe843b0b9f54ab2e58...,26508.0,True,2018.0,486.0,680.0,174.0,2018-12-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6590749,45d3pteh2TnzUMMl27J4MY,Tommy Morgan,78.0,15,singer,-,[],https://i.scdn.co/image/1c5cb45ccb80438b72a98a...,1193.0,True,1975.0,52.0,52.0,5.0,1975-06-14
6590750,45d3pteh2TnzUMMl27J4MY,Tommy Morgan,78.0,15,singer,-,[],https://i.scdn.co/image/1c5cb45ccb80438b72a98a...,1193.0,True,1975.0,41.0,41.0,4.0,1975-06-07
6590751,45d3pteh2TnzUMMl27J4MY,Tommy Morgan,78.0,15,singer,-,[],https://i.scdn.co/image/1c5cb45ccb80438b72a98a...,1193.0,True,1975.0,30.0,30.0,3.0,1975-05-31
6590752,45d3pteh2TnzUMMl27J4MY,Tommy Morgan,78.0,15,singer,-,[],https://i.scdn.co/image/1c5cb45ccb80438b72a98a...,1193.0,True,1975.0,19.0,19.0,2.0,1975-05-24
6590753,45d3pteh2TnzUMMl27J4MY,Tommy Morgan,78.0,15,singer,-,[],https://i.scdn.co/image/1c5cb45ccb80438b72a98a...,1193.0,True,1975.0,8.0,8.0,0.0,1975-05-17

In [29]:
df2.columns

Index(['artist_id', 'name', 'followers', 'popularity', 'artist_type',
       'main_genre', 'genres', 'image_url', 'year_end_score', 'is_pop', 'year',
       'rank_score', 'peak_position', 'weeks_on_chart', 'week'],
      dtype='object')

In [23]:
df3 = pd.read_csv('songs_popularity.csv', sep='\t')
df3

/var/folders/nw/0j298g817b92m2qlhw1_fwnr0000gn/T/ipykernel_42300/3624914712.py:1: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  df3 = pd.read_csv('songs_popularity.csv', sep='\t')

,song_id,song_name,billboard,artists,popularity,explicit,song_type,duration_ms,key,mode,...,valence,tempo,lyrics,year_end_score,is_pop,year,rank_score,peak_position,weeks_on_chart,week
0,3e9HZxeyfWwjeyPAMmWSSQ,"thank u, next","('Thank U, Next', 'Ariana Grande')",{'66CXWjxzNUsdJxJ2JdwvnR': 'Ariana Grande'},86,True,Solo,207320,1,1,...,0.412,106.966,['[Verse 1]\nThought I\'d end up with Sean\nBu...,728.0,True,2018.0,100.0,100.0,7.0,2018-12-29
1,3e9HZxeyfWwjeyPAMmWSSQ,"thank u, next","('Thank U, Next', 'Ariana Grande')",{'66CXWjxzNUsdJxJ2JdwvnR': 'Ariana Grande'},86,True,Solo,207320,1,1,...,0.412,106.966,['[Verse 1]\nThought I\'d end up with Sean\nBu...,728.0,True,2018.0,100.0,100.0,6.0,2018-12-22
2,3e9HZxeyfWwjeyPAMmWSSQ,"thank u, next","('Thank U, Next', 'Ariana Grande')",{'66CXWjxzNUsdJxJ2JdwvnR': 'Ariana Grande'},86,True,Solo,207320,1,1,...,0.412,106.966,['[Verse 1]\nThought I\'d end up with Sean\nBu...,728.0,True,2018.0,100.0,100.0,5.0,2018-12-15
3,3e9HZxeyfWwjeyPAMmWSSQ,"thank u, next","('Thank U, Next', 'Ariana Grande')",{'66CXWjxzNUsdJxJ2JdwvnR': 'Ariana Grande'},86,True,Solo,207320,1,1,...,0.412,106.966,['[Verse 1]\nThought I\'d end up with Sean\nBu...,728.0,True,2018.0,99.0,100.0,4.0,2018-12-08
4,3e9HZxeyfWwjeyPAMmWSSQ,"thank u, next","('Thank U, Next', 'Ariana Grande')",{'66CXWjxzNUsdJxJ2JdwvnR': 'Ariana Grande'},86,True,Solo,207320,1,1,...,0.412,106.966,['[Verse 1]\nThought I\'d end up with Sean\nBu...,728.0,True,2018.0,100.0,100.0,3.0,2018-12-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339339,2H9CKpZiLDF223BbwehpDF,Hush Hush,"('Hush Hush', 'The Pussycat Dolls Featuring Ni...",{'6wPhSqRtPu1UhRCDX5yaDJ': 'The Pussycat Dolls'},57,False,Solo,252093,10,0,...,0.664,129.334,NaN,273.0,False,2009.0,26.0,28.0,5.0,2009-08-08
339340,2H9CKpZiLDF223BbwehpDF,Hush Hush,"('Hush Hush', 'The Pussycat Dolls Featuring Ni...",{'6wPhSqRtPu1UhRCDX5yaDJ': 'The Pussycat Dolls'},57,False,Solo,252093,10,0,...,0.664,129.334,NaN,273.0,False,2009.0,18.0,28.0,4.0,2009-08-01
339341,2H9CKpZiLDF223BbwehpDF,Hush Hush,"('Hush Hush', 'The Pussycat Dolls Featuring Ni...",{'6wPhSqRtPu1UhRCDX5yaDJ': 'The Pussycat Dolls'},57,False,Solo,252093,10,0,...,0.664,129.334,NaN,273.0,False,2009.0,16.0,28.0,3.0,2009-07-25
339342,2H9CKpZiLDF223BbwehpDF,Hush Hush,"('Hush Hush', 'The Pussycat Dolls Featuring Ni...",{'6wPhSqRtPu1UhRCDX5yaDJ': 'The Pussycat Dolls'},57,False,Solo,252093,10,0,...,0.664,129.334,NaN,273.0,False,2009.0,28.0,28.0,2.0,2009-07-18
339343,2H9CKpZiLDF223BbwehpDF,Hush Hush,"('Hush Hush', 'The Pussycat Dolls Featuring Ni...",{'6wPhSqRtPu1UhRCDX5yaDJ': 'The Pussycat Dolls'},57,False,Solo,252093,10,0,...,0.664,129.334,NaN,273.0,False,2009.0,5.0,5.0,0.0,2009-05-30

In [55]:
artist_year_scores = df2.groupby(['name', 'year'])['year_end_score'].sum().reset_index()
artist_year_scores = artist_year_scores.sort_values(by = 'year')
artist_year_scores = artist_year_scores[artist_year_scores["name"] != "Various Artists"]

artist_year_scores

                          name    year  year_end_score
30299              The Animals  1964.0       1023891.0
10057            Elvis Presley  1964.0      14781126.0
11315           Frank Fontaine  1964.0         13536.0
820                    Al Hirt  1964.0       3839165.0
15821  John Fitzgerald Kennedy  1964.0         13869.0
...                        ...     ...             ...
20507            Mayday Parade  2018.0          1552.0
33436              The Wombats  2018.0            22.0
20583                Meek Mill  2018.0        867510.0
19985             Mariah Carey  2018.0       2844055.0
8575              Denzel Curry  2018.0          2804.0

[36546 rows x 3 columns]

In [57]:
# download artist_year_scores.csv
artist_year_scores.to_csv('artist_year_scores.csv', sep=',', index=False)

In [26]:
# drop these features from df3 year_end_score	is_pop	year	rank_score	peak_position	weeks_on_chart	week
df4 = df3[['song_id','song_name', 'popularity','danceability','energy','valence','acousticness','speechiness']]
df4

,song_id,song_name,popularity,danceability,energy,valence,acousticness,speechiness
0,3e9HZxeyfWwjeyPAMmWSSQ,"thank u, next",86,0.717,0.653,0.412,0.229,0.0658
1,3e9HZxeyfWwjeyPAMmWSSQ,"thank u, next",86,0.717,0.653,0.412,0.229,0.0658
2,3e9HZxeyfWwjeyPAMmWSSQ,"thank u, next",86,0.717,0.653,0.412,0.229,0.0658
3,3e9HZxeyfWwjeyPAMmWSSQ,"thank u, next",86,0.717,0.653,0.412,0.229,0.0658
4,3e9HZxeyfWwjeyPAMmWSSQ,"thank u, next",86,0.717,0.653,0.412,0.229,0.0658
...,...,...,...,...,...,...,...,...
339339,2H9CKpZiLDF223BbwehpDF,Hush Hush,57,0.609,0.790,0.664,0.105,0.0663
339340,2H9CKpZiLDF223BbwehpDF,Hush Hush,57,0.609,0.790,0.664,0.105,0.0663
339341,2H9CKpZiLDF223BbwehpDF,Hush Hush,57,0.609,0.790,0.664,0.105,0.0663
339342,2H9CKpZiLDF223BbwehpDF,Hush Hush,57,0.609,0.790,0.664,0.105,0.0663
339343,2H9CKpZiLDF223BbwehpDF,Hush Hush,57,0.609,0.790,0.664,0.105,0.0663

In [27]:
# keep only unique song_ids
df4_unique = df4.drop_duplicates(subset=['song_id'])
df4_unique

,song_id,song_name,popularity,danceability,energy,valence,acousticness,speechiness
0,3e9HZxeyfWwjeyPAMmWSSQ,"thank u, next",86,0.717,0.653,0.412,0.229000,0.0658
7,5p7ujcrUXASCNwRaWNHR1C,Without Me,87,0.752,0.488,0.533,0.297000,0.0705
18,2xLMifQCjDGFmkHkpNLD9h,SICKO MODE,85,0.834,0.730,0.446,0.005130,0.2220
38,3KkXRkHbMCARz0aVfEt68P,Sunflower - Spider-Man: Into the Spider-Verse,92,0.760,0.479,0.913,0.556000,0.0466
47,1rqqCSm0Qe4I9rUvWncaom,High Hopes,86,0.579,0.904,0.681,0.193000,0.0618
...,...,...,...,...,...,...,...,...
339311,4NnhLA66RRLXxKbiiscU9R,How Can I Be Sure - Single Version,36,0.231,0.455,0.391,0.841000,0.0296
339322,2jHfXdCLibrI1J56LnUAZv,To Show I Love You - Mono,1,0.239,0.598,0.829,0.195000,0.0416
339324,6zqsyB7uIvWrL1iCJzpNrs,You Better Run - Single Version,20,0.422,0.494,0.723,0.000942,0.0528
339331,5mz9pQZZXNpAw9CdQ7Bk8q,Don't Pity Me - Mono,7,0.500,0.654,0.403,0.619000,0.0394
339335,2H9CKpZiLDF223BbwehpDF,Hush Hush,57,0.609,0.790,0.664,0.105000,0.0663

In [47]:
# download df4unique as unique_songs.csv
df4_unique.to_csv('unique_songs.csv', sep=',', index=False)

In [35]:
df

,song_id,album_id,track_number,release_date_x,release_date_precision_x,name,billboard,artists,popularity,total_tracks,...,year_end_score,is_pop,year,rank_score,peak_position,week_count,date,artist_id,release_date_y,release_date_precision_y
0,3e9HZxeyfWwjeyPAMmWSSQ,2fYhqwDWXjbpjaIJPEfKFw,11,2019-02-08,day,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5p7ujcrUXASCNwRaWNHR1C,0zzrCTzvL4ZmR42xF46Afm,1,2018-10-04,day,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2xLMifQCjDGFmkHkpNLD9h,41GuZcammIkupMPKH2OJ6I,3,2018-08-03,day,ASTROWORLD,ASTROWORLD,{'0Y5tJX1MQlPlqiwlOH1tJY': 'Travis Scott'},91.0,17.0,...,4210.0,True,2018.0,195.0,200.0,20.0,2018-12-29,0Y5tJX1MQlPlqiwlOH1tJY,2018-08-03,day
3,2xLMifQCjDGFmkHkpNLD9h,41GuZcammIkupMPKH2OJ6I,3,2018-08-03,day,ASTROWORLD,ASTROWORLD,{'0Y5tJX1MQlPlqiwlOH1tJY': 'Travis Scott'},91.0,17.0,...,4210.0,True,2018.0,195.0,200.0,19.0,2018-12-22,0Y5tJX1MQlPlqiwlOH1tJY,2018-08-03,day
4,2xLMifQCjDGFmkHkpNLD9h,41GuZcammIkupMPKH2OJ6I,3,2018-08-03,day,ASTROWORLD,ASTROWORLD,{'0Y5tJX1MQlPlqiwlOH1tJY': 'Travis Scott'},91.0,17.0,...,4210.0,True,2018.0,193.0,200.0,18.0,2018-12-15,0Y5tJX1MQlPlqiwlOH1tJY,2018-08-03,day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1986380,30342v7I9sUoNC0Djnu1mW,1bZHbHtUvjGqUOKNla4lo0,25,2000-01-01,day,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1986381,5rkgbGIOTBGlKTAawWb06X,3GmCXW10kLxmZrEY0JpRlw,9,1988-03-07,day,Past Masters (Vols. 1 & 2 / Remastered),Past Masters,{'3WrFJ7ztbogyGnTHbHJFl2': 'The Beatles'},61.0,33.0,...,73.0,False,2010.0,47.0,47.0,2.0,2010-01-09,3WrFJ7ztbogyGnTHbHJFl2,1988-03-07,day
1986382,5rkgbGIOTBGlKTAawWb06X,3GmCXW10kLxmZrEY0JpRlw,9,1988-03-07,day,Past Masters (Vols. 1 & 2 / Remastered),Past Masters,{'3WrFJ7ztbogyGnTHbHJFl2': 'The Beatles'},61.0,33.0,...,73.0,False,2010.0,24.0,24.0,0.0,2010-01-02,3WrFJ7ztbogyGnTHbHJFl2,1988-03-07,day
1986383,2MVPsa4S4r7Ii5lMh85E03,0UiVuqXa69zXqql0GoXH2h,22,2013-01-31,day,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1986384,7wGbzk3aeGSpnsK2AQ7vzA,3pBArpt3QcnvVj58hl6Ghe,7,2012-05-31,day,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
# only display unique song_ids in df
df_unique = df.drop_duplicates(subset=['song_id'])
df_unique

,song_id,album_id,track_number,release_date_x,release_date_precision_x,name,billboard,artists,popularity,total_tracks,...,year_end_score,is_pop,year,rank_score,peak_position,week_count,date,artist_id,release_date_y,release_date_precision_y
0,3e9HZxeyfWwjeyPAMmWSSQ,2fYhqwDWXjbpjaIJPEfKFw,11,2019-02-08,day,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5p7ujcrUXASCNwRaWNHR1C,0zzrCTzvL4ZmR42xF46Afm,1,2018-10-04,day,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2xLMifQCjDGFmkHkpNLD9h,41GuZcammIkupMPKH2OJ6I,3,2018-08-03,day,ASTROWORLD,ASTROWORLD,{'0Y5tJX1MQlPlqiwlOH1tJY': 'Travis Scott'},91.0,17.0,...,4210.0,True,2018.0,195.0,200.0,20.0,2018-12-29,0Y5tJX1MQlPlqiwlOH1tJY,2018-08-03,day
22,3KkXRkHbMCARz0aVfEt68P,35s58BRTGAEWztPo9WqCIs,2,2018-12-14,day,Spider-Man: Into the Spider-Verse (Soundtrack ...,Spider-Man: Into The Spider-Verse,{'0LyfQWJT6nXafLPZqxe9Of': 'Various Artists'},92.0,13.0,...,196.0,False,2018.0,196.0,196.0,0.0,2018-12-29,0LyfQWJT6nXafLPZqxe9Of,2018-12-14,day
206,1rqqCSm0Qe4I9rUvWncaom,6ApYSpXF8GxZAgBTHDzYge,4,2018-06-22,day,Pray for the Wicked,Pray For The Wicked,{'20JZFwl6HVl6yg8a4H3ZqK': 'Panic! At The Disco'},87.0,11.0,...,5551.0,True,2018.0,160.0,200.0,26.0,2018-12-29,20JZFwl6HVl6yg8a4H3ZqK,2018-06-22,day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1986379,0yZsBLZVU2HTMlMqYvWevJ,5UoKanu6wcBQhwfPSDHYVw,4,2011-04-01,day,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1986380,30342v7I9sUoNC0Djnu1mW,1bZHbHtUvjGqUOKNla4lo0,25,2000-01-01,day,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1986381,5rkgbGIOTBGlKTAawWb06X,3GmCXW10kLxmZrEY0JpRlw,9,1988-03-07,day,Past Masters (Vols. 1 & 2 / Remastered),Past Masters,{'3WrFJ7ztbogyGnTHbHJFl2': 'The Beatles'},61.0,33.0,...,73.0,False,2010.0,47.0,47.0,2.0,2010-01-09,3WrFJ7ztbogyGnTHbHJFl2,1988-03-07,day
1986383,2MVPsa4S4r7Ii5lMh85E03,0UiVuqXa69zXqql0GoXH2h,22,2013-01-31,day,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1986384,7wGbzk3aeGSpnsK2AQ7vzA,3pBArpt3QcnvVj58hl6Ghe,7,2012-05-31,day,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
df_unique['release_date_y'].isna().sum()

9105

In [38]:
df4_unique

,song_id,song_name,popularity,danceability,energy,valence,acousticness,speechiness
0,3e9HZxeyfWwjeyPAMmWSSQ,"thank u, next",86,0.717,0.653,0.412,0.229000,0.0658
7,5p7ujcrUXASCNwRaWNHR1C,Without Me,87,0.752,0.488,0.533,0.297000,0.0705
18,2xLMifQCjDGFmkHkpNLD9h,SICKO MODE,85,0.834,0.730,0.446,0.005130,0.2220
38,3KkXRkHbMCARz0aVfEt68P,Sunflower - Spider-Man: Into the Spider-Verse,92,0.760,0.479,0.913,0.556000,0.0466
47,1rqqCSm0Qe4I9rUvWncaom,High Hopes,86,0.579,0.904,0.681,0.193000,0.0618
...,...,...,...,...,...,...,...,...
339311,4NnhLA66RRLXxKbiiscU9R,How Can I Be Sure - Single Version,36,0.231,0.455,0.391,0.841000,0.0296
339322,2jHfXdCLibrI1J56LnUAZv,To Show I Love You - Mono,1,0.239,0.598,0.829,0.195000,0.0416
339324,6zqsyB7uIvWrL1iCJzpNrs,You Better Run - Single Version,20,0.422,0.494,0.723,0.000942,0.0528
339331,5mz9pQZZXNpAw9CdQ7Bk8q,Don't Pity Me - Mono,7,0.500,0.654,0.403,0.619000,0.0394
339335,2H9CKpZiLDF223BbwehpDF,Hush Hush,57,0.609,0.790,0.664,0.105000,0.0663

In [41]:
# Step 1: Create a lookup dictionary of song_id → is_billboard (True/False)
billboard_lookup = df_unique.set_index("song_id")["billboard"].notna()

# # Step 2: Map this to df4_unique using song_id
df4_unique["is_billboard"] = df4_unique["song_id"].map(billboard_lookup).fillna(False)

df4_unique

/var/folders/nw/0j298g817b92m2qlhw1_fwnr0000gn/T/ipykernel_42300/1809600161.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4_unique["is_billboard"] = df4_unique["song_id"].map(billboard_lookup).fillna(False)

,song_id,song_name,popularity,danceability,energy,valence,acousticness,speechiness,is_billboard
0,3e9HZxeyfWwjeyPAMmWSSQ,"thank u, next",86,0.717,0.653,0.412,0.229000,0.0658,False
7,5p7ujcrUXASCNwRaWNHR1C,Without Me,87,0.752,0.488,0.533,0.297000,0.0705,False
18,2xLMifQCjDGFmkHkpNLD9h,SICKO MODE,85,0.834,0.730,0.446,0.005130,0.2220,True
38,3KkXRkHbMCARz0aVfEt68P,Sunflower - Spider-Man: Into the Spider-Verse,92,0.760,0.479,0.913,0.556000,0.0466,True
47,1rqqCSm0Qe4I9rUvWncaom,High Hopes,86,0.579,0.904,0.681,0.193000,0.0618,True
...,...,...,...,...,...,...,...,...,...
339311,4NnhLA66RRLXxKbiiscU9R,How Can I Be Sure - Single Version,36,0.231,0.455,0.391,0.841000,0.0296,True
339322,2jHfXdCLibrI1J56LnUAZv,To Show I Love You - Mono,1,0.239,0.598,0.829,0.195000,0.0416,False
339324,6zqsyB7uIvWrL1iCJzpNrs,You Better Run - Single Version,20,0.422,0.494,0.723,0.000942,0.0528,True
339331,5mz9pQZZXNpAw9CdQ7Bk8q,Don't Pity Me - Mono,7,0.500,0.654,0.403,0.619000,0.0394,False
339335,2H9CKpZiLDF223BbwehpDF,Hush Hush,57,0.609,0.790,0.664,0.105000,0.0663,False

In [46]:
df4_unique

,song_id,song_name,popularity,danceability,energy,valence,acousticness,speechiness,is_billboard
0,3e9HZxeyfWwjeyPAMmWSSQ,"thank u, next",86,0.717,0.653,0.412,0.229000,0.0658,False
7,5p7ujcrUXASCNwRaWNHR1C,Without Me,87,0.752,0.488,0.533,0.297000,0.0705,False
18,2xLMifQCjDGFmkHkpNLD9h,SICKO MODE,85,0.834,0.730,0.446,0.005130,0.2220,True
38,3KkXRkHbMCARz0aVfEt68P,Sunflower - Spider-Man: Into the Spider-Verse,92,0.760,0.479,0.913,0.556000,0.0466,True
47,1rqqCSm0Qe4I9rUvWncaom,High Hopes,86,0.579,0.904,0.681,0.193000,0.0618,True
...,...,...,...,...,...,...,...,...,...
339311,4NnhLA66RRLXxKbiiscU9R,How Can I Be Sure - Single Version,36,0.231,0.455,0.391,0.841000,0.0296,True
339322,2jHfXdCLibrI1J56LnUAZv,To Show I Love You - Mono,1,0.239,0.598,0.829,0.195000,0.0416,False
339324,6zqsyB7uIvWrL1iCJzpNrs,You Better Run - Single Version,20,0.422,0.494,0.723,0.000942,0.0528,True
339331,5mz9pQZZXNpAw9CdQ7Bk8q,Don't Pity Me - Mono,7,0.500,0.654,0.403,0.619000,0.0394,False
339335,2H9CKpZiLDF223BbwehpDF,Hush Hush,57,0.609,0.790,0.664,0.105000,0.0663,False